package View;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.ListSelectionListener;

public class CustomerView extends JPanel {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private JButton searchButton;
	private DefaultListModel<String> listModel;
    private JList<String> searchResultField;
    private JScrollPane scrollPane1;
    private JButton deleteButton;
    private JComboBox<String> customerType;
    private JRadioButton idRadio;
    private JRadioButton nameRadio;
    private JRadioButton typeRadio;
    private JButton clearButton;
    private JButton addButton;
    private JButton modifyButton;
    private JTextField searchText;
    private JTextField customerIdText;
    private JTextField firstNameText;
    private JTextField lastNameText;
    private JTextField addressText;
    private JTextField postalText;
    private JTextField phoneText;
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JLabel jcomp7;
    private JLabel jcomp8;
    private JLabel jcomp9;
    private JLabel jcomp10;
    private JLabel jcomp11;
    private JButton quitButton;

    public CustomerView() {
        setPreferredSize (new Dimension (1057, 600));
        setLayout (null);
        
        addSearchCustomer();
        addCustomerInformation();
        addLabels();
        
        quitButton = new JButton("Quit");
        add(quitButton);
        quitButton.setBounds (470, 550, 100, 20);
        
    }
    
    //-----------------------------------------
    // ACTION LISTENERS
    public void addClearListener(ActionListener clear) {
    	clearButton.addActionListener(clear);
    }
    
    public void addQuitListener(ActionListener quit) {
    	quitButton.addActionListener(quit);
    }
    
    //-----------------------------------------
    // FOR POP-UPS
    public void showError(String errMessage) {
        JOptionPane.showMessageDialog(this, errMessage);
    }
    
    //---------------------------------------------------------------------------------------
    // FOR SEARCHING CUSTOMERS BY ID, NAME, OR TYPE
    //---------------------------------------------------------------------------------------

    private void addSearchCustomer() {
    	searchButton = new JButton ("Search");   
    	searchText = new JTextField (5);
    	
    	listModel = new DefaultListModel<String>();
        searchResultField = new JList<String> (listModel);
        scrollPane1 = new JScrollPane(searchResultField);
        
        ButtonGroup group = new ButtonGroup();
        idRadio = new JRadioButton ("id");
        nameRadio = new JRadioButton ("name");
        typeRadio = new JRadioButton ("type");
        group.add(idRadio);
        group.add(nameRadio);
        group.add(typeRadio);
        
        add (searchButton);
        add (scrollPane1);
        add (searchText);
        add (idRadio);
        add (nameRadio);
        add (typeRadio);
        
        searchButton.setBounds (345, 170, 100, 20);
        scrollPane1.setBounds (110, 205, 455, 310);
        searchText.setBounds (110, 165, 215, 25);
        idRadio.setBounds (110, 130, 55, 25);
        nameRadio.setBounds (165, 130, 65, 25);
        typeRadio.setBounds (235, 130, 55, 25);
    }
    
    //-----------------------------------------
    // Search Text Field
    public String getSearchText() {
    	return searchText.getText();
    }
    
    //-----------------------------------------
    // Search Type Field
    public String getSearchType() {
    	if(idRadio.isSelected()) 
    		return idRadio.getText();
    	
    	if(nameRadio.isSelected())
    		return nameRadio.getText();
    	
    	if(typeRadio.isSelected())
    		return typeRadio.getText();
    	
    	return null;
    }
    
    //-----------------------------------------
    // Search Results Field
    public JList<String> getSearchList(){
    	return searchResultField;
    }
    public DefaultListModel<String> getListModel(){
    	return listModel;
    }
    
    //-----------------------------------------
    // ACTION LISTENERS
    public void addSearchListener(ActionListener search) {
    	searchButton.addActionListener(search);
    }
       
    public void addSearchListListener(ListSelectionListener search) {
    	searchResultField.addListSelectionListener(search);
    }
       
    //---------------------------------------------------------------------------------------
    // FOR CUSTOMER INFORMATION, INCLUDES ADDING, MODIFYING, OR DELETING CUSTOMERS
    //---------------------------------------------------------------------------------------
    private void addCustomerInformation() {
    	String[] customerTypeItems = {"Residential", "Commercial"};
    	
        deleteButton = new JButton ("Delete");
        customerType = new JComboBox<String> (customerTypeItems);
        clearButton = new JButton ("Clear");
        addButton = new JButton ("Add");
        modifyButton = new JButton ("Save");
        customerIdText = new JTextField (5);
        firstNameText = new JTextField (5);
        lastNameText = new JTextField (5);
        addressText = new JTextField (5);
        postalText = new JTextField (5);
        phoneText = new JTextField (5);
        
        add (deleteButton);
        add (customerType);
        add (clearButton);
        add (addButton);
        add (modifyButton);
        add (customerIdText);
        add (firstNameText);
        add (lastNameText);
        add (addressText);
        add (postalText);
        add (phoneText);
        
        deleteButton.setBounds (875, 435, 100, 25);
        customerType.setBounds (790, 340, 200, 30);
        clearButton.setBounds (755, 485, 100, 25);
        addButton.setBounds (630, 435, 100, 25);
        modifyButton.setBounds (755, 435, 100, 25);
        customerIdText.setBounds (790, 100, 200, 25);
        firstNameText.setBounds (790, 140, 200, 25);
        lastNameText.setBounds (790, 180, 200, 25);
        addressText.setBounds (790, 220, 200, 25);
        postalText.setBounds (790, 260, 200, 25);
        phoneText.setBounds (790, 300, 200, 25);
    }
    
    //-----------------------------------------
    // Customer Id Field
    public JTextField getCustomerIdField() {
    	return customerIdText;
    }
    public String getCustomerIdText() {
    	return customerIdText.getText();
    }
    
    //-----------------------------------------
    // First Name Field
    public JTextField getFirstNameField() {
    	return firstNameText;
    }
    public String getFirstNameText() {
    	return firstNameText.getText();
    }
    
    //-----------------------------------------
    // Last Name Field
    public JTextField getLastNameField() {
    	return lastNameText;
    }
    public String getLastNameText() {
    	return lastNameText.getText();
    }
    
    //-----------------------------------------
    // Address Field
    public JTextField getAddressField() {
    	return addressText;
    }
    public String getAddressText() {
    	return addressText.getText();
    }
    
    //-----------------------------------------
    // Postal Code Field
    public JTextField getPostalField() {
    	return postalText;
    }
    public String getPostalText() {
    	return postalText.getText();
    }
    
    //-----------------------------------------
    // Phone Number Field
    public JTextField getPhoneField() {
    	return phoneText;
    }
    public String getPhoneText() {
    	return phoneText.getText();
    }
    
    //-----------------------------------------
    // Cusotmer Type Field
    public JComboBox<String> getCustomerTypeField() {
    	return customerType;
    }
    public String getCustomerTypeText() {
    	return (String) customerType.getSelectedItem();
    }
    
    //-----------------------------------------
    // ACTION LISTENERS
    public void addDeleteListener(ActionListener del) {
    	deleteButton.addActionListener(del);
    }
    
    public void addModifyListener(ActionListener mod) {
    	modifyButton.addActionListener(mod);
    }
    
    public void addAddListener(ActionListener add) {
    	addButton.addActionListener(add);
    }
        
    //---------------------------------------------------------------------------------------
    // LABELS IN THE JFRAME
    //---------------------------------------------------------------------------------------
    private void addLabels() {
    	jcomp1 = new JLabel ("Postal Code");
    	jcomp2 = new JLabel ("CUSTOMER MANAGEMENT");
        jcomp3 = new JLabel ("Address");
        jcomp4 = new JLabel ("Last Name");
        jcomp5 = new JLabel ("First Name");
        jcomp6 = new JLabel ("Customer Id");
        jcomp7 = new JLabel ("Search Customers By:");
        jcomp8 = new JLabel ("Customer Type");
        jcomp9 = new JLabel ("Customer Information");
        jcomp10 = new JLabel ("Search Customers");
        jcomp11 = new JLabel ("Phone Number");
        
        add(jcomp1);
        add(jcomp2);
        add(jcomp3);
        add(jcomp4);
        add(jcomp5);
        add(jcomp6);
        add(jcomp7);
        add(jcomp8);
        add(jcomp9);
        add(jcomp10);
        add(jcomp11);
        
        jcomp1.setBounds (690, 260, 100, 30);
        jcomp2.setBounds (455, 5, 180, 40);
        jcomp3.setBounds (690, 220, 100, 30);
        jcomp4.setBounds (690, 180, 100, 30);
        jcomp5.setBounds (690, 140, 100, 30);
        jcomp6.setBounds (690, 100, 100, 30);
        jcomp7.setBounds (115, 95, 140, 25);
        jcomp8.setBounds (690, 340, 100, 30);
        jcomp9.setBounds (730, 50, 140, 25);
        jcomp10.setBounds (165, 50, 113, 25);
        jcomp11.setBounds (690, 300, 100, 30);
    }   
}
